# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-18 21:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('PokerPlanner', '0002_auto_20180113_2013'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pokerplayer',
            name='is_currently_in_game',
        ),
    ]
