# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-18 23:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('PokerPlanner', '0004_auto_20180119_0020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scrumstory',
            name='dateCompleted',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='scrumstory',
            name='story_points',
            field=models.IntegerField(null=True),
        ),
    ]
