# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-29 10:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('PokerPlanner', '0005_auto_20180119_0030'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pokergame',
            name='table',
        ),
        migrations.AlterField(
            model_name='scrumstory',
            name='dateCompleted',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='scrumstory',
            name='story_points',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='PokerTable',
        ),
    ]
